# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: stderr_test

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    user: pnlbwh
    wd: /home

  steps: 
 
  - script: |
        curl -LOs https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        ./container-structure-test-linux-amd64 --help
    displayName: 'What does curl write to stderr'
    failOnStderr: true
    
    
